#mybatis:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
  redis:
    database: 0
    host: 121.40.174.157
    port: 6379
    lettuce:
      pool:
        min-idle: 1
    timeout: 3000
    password: 123456