mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        min-idle: 1
    timeout: 3000